modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "magmavision"
version = "${version}"
displayName = "Magma Vision"
authors = "Me!"
description = '''
${version}
'''
logoFile = "logo.png"

[[mixins]]
config = "magmavision.mixins.json"
[[mixins]]
config = "magmavision.forge.mixins.json"


[[dependencies.magmavision]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.magmavision]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.magmavision]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
